spring.application.name=ecommerce

# Postgre SQL
spring.datasource.url=jdbc:postgresql://localhost:5432/dbecommerce?ApplicationName=ecommerce
spring.datasource.username=user_ecommerce
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
# Connection Pool
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.connection-test-query=select 1 valid_connection

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.default_schema=public

# Logging
logging.level.root=INFO
spring.output.ansi.enabled=ALWAYS